export const GET_LOGIN_DATA = "GET_LOGIN_DATA";
export const GET_LOGIN_DATA_SUCCESS = "GET_LOGIN_DATA_SUCCESS";
export const GET_LOGIN_DATA_FAIL = "GET_LOGIN_DATA_FAIL";
export const UPDATE_LOGIN = "UPDATE_LOGIN";
