export const GET_DATA = "GET_DATA";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";
export const GET_NO_OF_CLAIMS = "GET_NO_OF_CLAIMS";
export const GET_NO_OF_CLAIMS_SUCCESS = "GET_NO_OF_CLAIMS_SUCCESS";
export const GET_NO_OF_CLAIMS_FAIL = "GET_NO_OF_CLAIMS_FAIL";
